#!/bin/sh

killall -q polybar; polybar &
killall -q conky &
killall -q picom &
killall -q nitrogen; nitrogen --restore &
killall -q sxhkd; sxhkd &
setxkbmap cz &
xsetroot -cursor_name left_ptr &
#LD_PRELOAD=/home/woox/spotifywm/spotifywm.so /usr/share/spotify/spotify
#. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d 1 2 3 4 5

# Padding from sides so it looks better
bspc config top_padding            20
bspc config bottom_padding         20
bspc config left_padding           20
bspc config right_padding          20

# General configuration
bspc config pointer_motion_interval 5
bspc config focus_follows_pointer   false
bspc config ignore_ewmh_focus       true
bspc config pointer_follows_monitor true
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# Window & border configuration
bspc config border_width  0
bspc config window_gap    18

bspc config split_ratio          0.52
#bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Set the border colors.
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"

#bspc config focused_border_color "#98ffff"
#bspc config normal_border_color  "#98ffff"
#bspc config unfocused_border_color  "#ffffff"

# Ordering windows
#bspc rule -a kitty           desktop='^1' follow=on
bspc rule -a firefox         desktop='^2' follow=on
bspc rule -a LeagueClient.exe desktop='^4' state=floating
bspc rule -a Nitrogen        state=floating
bspc rule -a discord         desktop='^4' state=floating center=on
bspc rule -a spotify         desktop='^4' state=floating follow=on center=on
bspc rule -a Steam           desktop='^3' state=floating center=on
bspc rule -a lunarclient     desktop='^3' state=floating follow=on center=on
bspc rule -a 'Steam:*:Friends List' desktop='^3' state=floating
bspc rule -a java            desktop='^5' state=floating
bspc rule -a Lutris          desktop='^3'
bspc rule -a cutefish-filemanager state=floating
bspc rule -a Code            desktop='^4' follow=on
bspc rule -a qBittorrent     desktop='^1' follow=on
bspc rule -a cutefish-*          state=floating

bspc rule -a feh                state=floating
bspc rule -a Org.gnome.Nautilus state=floating

# games
bspc rule -a robloxplayerlauncher.exe desktop='^4' state=floating
bspc rule -a robloxplayerbeta.exe     desktop='^4' state=floating
bspc rule -a leagueoflegends.exe      desktop='^4' state=floating

bspc rule -a hl2_linux                desktop='^5'
#bspc rule -a *.exe                    desktop='^4' state=floating

#steamlib=/media/gamedisk/SteamLibrary
#mygames=$(ls $steamlib/steamapps/appmanifest_*.acf | sed 's/[^0-9]*//g')
#
#for game in $mygames; do
#  bspc rule -a steam_app_$game desktop=^4
#done


setxkbmap -option grp:alt_shift_toggle cz,us & # Keyboard layout switch 


#   ▒▄▀▄░█▒█░▀█▀░▄▀▄░▄▀▀░▀█▀▒▄▀▄▒█▀▄░▀█▀ #
#   ░█▀█░▀▄█░▒█▒░▀▄▀▒▄██░▒█▒░█▀█░█▀▄░▒█▒ #

killall -q dunst; dunst & #Kills dunst if it's running and launches it again
polybar & # Polybar - Status bar
nitrogen --restore & # Restores and changes my last wallpaper
discord &
steam &
conky -c $HOME/.config/conky/catppuccin.conf &
picom &
#wal -i ~/Pictures/leaves1.jpg 
